### ISSUE TITLE
Client SDK: Potential regression in Client SDK <-> Daemon transaction compatibility.

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#5234] opened 2020-06-26 23:05 UTC
I couldn't find an issue on this tracked on GitHub so I made one here.

Reports of "invalid signature" errors when using the offline client SDK to generate transactions and feed them on the 3.2b testnet. cc @garethtdavies

**Comment by garethtdavies** [comment] 2020-06-27 01:10
Thanks, as was just about to make an issue for this and seems simple to repro if it is a bug. Here's a sample signed message generated from `CodaSDK.signPayment`:

```
{
  "publicKey": "4vsRCVjVZaBEBa9mWThrsBQ48uCWyzpNKHnXKPTjG6xfUbWC5L9ZhpnwVKBps9MydU3TrVa93qXHbb5pcznvAmg2CbTLFnPtiyyX2W1XHHSCiPkumYFEWUXFfwhTBjYfUVxRdKgoQinw74Wg",
  "signature": {
    "field": "38996859757695201711116184822668917641805648286752536623008950679075419987653460171835065078476259663526860315989192768134477252632547751949169343876634727964467673302873933778082560773769917273186977178385714112018702266130196",
    "scalar": "4278006856205276445182325844008242866512507616415328092844028977412262189984769032608174329842146234719154325781821764523357743453871357701855463826439384497373182113880439349108615581131612219493378082217008821162916543798031"
  },
  "payload": {
    "to": "4vsRCVGPNFDmHvuCctawApbyUg8J6iWzdHvJ2bNP8AL1GtMeaLwC6P8ZNTavKmAD4mMGbDq8H6DYramtiQP5fcf5xhdqAfYibt7Am9syUUU91oSf7HhLKrA26RPutsoyQSmZiMjPZoe1vDXW",
    "from": "4vsRCVjVZaBEBa9mWThrsBQ48uCWyzpNKHnXKPTjG6xfUbWC5L9ZhpnwVKBps9MydU3TrVa93qXHbb5pcznvAmg2CbTLFnPtiyyX2W1XHHSCiPkumYFEWUXFfwhTBjYfUVxRdKgoQinw74Wg",
    "fee": "1000000000",
    "amount": "1000000000",
    "nonce": "0",
    "memo": "",
    "validUntil": "4294967295"
  }
}
```

and the resulting query:

```
mutation sendPayment {
  sendPayment(input: {
    fee: "1000000000",
    amount: "1000000000",
    to: "4vsRCVGPNFDmHvuCctawApbyUg8J6iWzdHvJ2bNP8AL1GtMeaLwC6P8ZNTavKmAD4mMGbDq8H6DYramtiQP5fcf5xhdqAfYibt7Am9syUUU91oSf7HhLKrA26RPutsoyQSmZiMjPZoe1vDXW",
    from: "4vsRCVjVZaBEBa9mWThrsBQ48uCWyzpNKHnXKPTjG6xfUbWC5L9ZhpnwVKBps9MydU3TrVa93qXHbb5pcznvAmg2CbTLFnPtiyyX2W1XHHSCiPkumYFEWUXFfwhTBjYfUVxRdKgoQinw74Wg",
    validUntil: "4294967295"
  }, signature: {
    scalar: "4278006856205276445182325844008242866512507616415328092844028977412262189984769032608174329842146234719154325781821764523357743453871357701855463826439384497373182113880439349108615581131612219493378082217008821162916543798031",
    field: "38996859757695201711116184822668917641805648286752536623008950679075419987653460171835065078476259663526860315989192768134477252632547751949169343876634727964467673302873933778082560773769917273186977178385714112018702266130196"
  }) {
    payment {
      id
    }
  }
}
```

and the resulting message:

```
{
  "errors": [{
    "message": "Couldn't send user_command: Error creating user command: {\"payload\":{\"common\":{\"fee\":\"1\",\"fee_token\":\"1\",\"fee_payer_pk\":\"4vsRCVjVZaBEBa9mWThrsBQ48uCWyzpNKHnXKPTjG6xfUbWC5L9ZhpnwVKBps9MydU3TrVa93qXHbb5pcznvAmg2CbTLFnPtiyyX2W1XHHSCiPkumYFEWUXFfwhTBjYfUVxRdKgoQinw74Wg\",\"nonce\":null,\"valid_until\":\"4294967295\",\"memo\":\"E4YM2vTHhWEg66xpj52JErHUBU4pZ1yageL4TVDDpTTSsv8mK6YaH\"},\"body\":[\"Payment\",{\"source_pk\":\"4vsRCVjVZaBEBa9mWThrsBQ48uCWyzpNKHnXKPTjG6xfUbWC5L9ZhpnwVKBps9MydU3TrVa93qXHbb5pcznvAmg2CbTLFnPtiyyX2W1XHHSCiPkumYFEWUXFfwhTBjYfUVxRdKgoQinw74Wg\",\"receiver_pk\":\"4vsRCVGPNFDmHvuCctawApbyUg8J6iWzdHvJ2bNP8AL1GtMeaLwC6P8ZNTavKmAD4mMGbDq8H6DYramtiQP5fcf5xhdqAfYibt7Am9syUUU91oSf7HhLKrA26RPutsoyQSmZiMjPZoe1vDXW\",\"token_id\":\"1\",\"amount\":\"1000000000\"}]},\"signer\":\"4vsRCVjVZaBEBa9mWThrsBQ48uCWyzpNKHnXKPTjG6xfUbWC5L9ZhpnwVKBps9MydU3TrVa93qXHbb5pcznvAmg2CbTLFnPtiyyX2W1XHHSCiPkumYFEWUXFfwhTBjYfUVxRdKgoQinw74Wg\",\"signature\":[\"Signature\",\"22Yqx5K7XigEfNSH2H8ogmRuzHdsXRGoJoETtWca3FEfYe7W4DySiXfwkCdBy6Ds1vUHBH73FkBxRK4ff8EpNn5HPdLXCg3BSxjE9XGnjWefkSS2VT2dUvC5edua4VCsqE2R1itahxeKnQ1zpGR3gii6RpfnLcThA21RHzGyTREeXzyGyG1u3nxRTDV8KytxkBJGF2jMTCuTyMJV6SKmZsGsU5iodwumuCtisPLLAf1nEfRnG7dvHK52oFtsMfdfncm2zutGky8g9DUvCG\"]} Error: Invalid_signature",
    "path": [
      "sendPayment"
    ]
  }],
  "data": null
}
```

**Comment by bkase** [comment] 2020-06-29 20:55
@garethtdavies Are you sure your nonce is correct? I wonder if that's causing the issue? Anyway, we'll triage this and try and repro and root-cause soon!

**Comment by garethtdavies** [comment] 2020-06-29 21:08
@bkase The nonce is correct, it's a new account I sent 100 Coda too so nonce is 0. This screenshot shows the nonce and balance of the account on the current testnet (obtained via GraphQL).

<img width="1256" alt="CleanShot 2020-06-29 at 14 04 58@2x" src="https://user-images.githubusercontent.com/135382/86056067-b01b2200-ba11-11ea-9567-a9bc7f28be12.png">

**Comment by garethtdavies** [comment] 2020-06-29 21:15
I also checked this by deliberately submitting the wrong nonce and get this error as expected:

`Error: Input nonce 1 different from inferred nonce 0`

**Comment by bkase** [comment] 2020-06-30 22:40
@garethtdavies are you using the version of client-sdk from the same commit we've released the testnet off of? `ef22dae964e2b7323ad578cfabc1e8040c9aec29` should be close enough. Or you can `coda version` and checkout that commit and then test.

Oh we probably forgot to re-release a new client-sdk to npm 🤦 . If you're using the npm one, I expect that's why it's failing

**Comment by garethtdavies** [comment] 2020-06-30 22:42
> Oh we probably forgot to re-release a new client-sdk to npm 🤦 . If you're using the npm one, I expect that's why it's failing

Yes, using npm so I'll test directly on that commit and report back but I imagine it's something as simple as that 😄

**Comment by psteckler** [comment] 2020-06-30 22:49
@garethtdavies you might try running `make client_sdk`, then `./scripts/compare_test_signatures.sh`.

That will tell you if the SDK-generated signatures verify with the SDK.

**Comment by psteckler** [comment] 2020-06-30 22:54
@bkase Which version should the npm package match? If it's the testnet version, should that be in the testnet release checklist?

**Comment by garethtdavies** [comment] 2020-07-01 02:17
> @garethtdavies With that commit, you might try running `make client_sdk`, then `./scripts/compare_test_signatures.sh`.
> 
> That will tell you if the SDK-generated signatures verify with the SDK.

@psteckler I couldn't get this to work. Tried with and without the Docker container but hit the same error:

```
$ make USEDOCKER=TRUE client_sdk
INFO Using Docker Named codabuilder-1000
Starting Build
Build complete
ulimit -s 65532 && (ulimit -n 10240 || true) && dune build src/app/client_sdk/client_sdk.bc.js --profile=nonconsensus_medium_curves
File "src/nonconsensus/coda_base/dune", line 20, characters 50-66:
20 |   (pps ppx_coda ppx_deriving.eq ppx_deriving.enum ppx_deriving.ord
                                                       ^^^^^^^^^^^^^^^^
Error: Ppx dependency on a non-ppx library "ppx_deriving.ord". If
"ppx_deriving.ord" is in fact a ppx rewriter library, it should have (kind
ppx_rewriter) in its dune file.
File "src/lib/ppx_coda/bin_io_unversioned.ml", line 20, characters 13-40:
Error: Unbound module Expansion_context
make: *** [Makefile:105: client_sdk] Error 1
```

**Comment by psteckler** [comment] 2020-07-01 17:01
@garethtdavies It looks like the versions of `ppx_deriving` and `ppxlib` don't match the code.

In `src/opam.export`, I see:
```
ppx_deriving.4.4.1
ppxlib.0.8.1
```
You can use `opam list` to see what's installed.

**Comment by garethtdavies** [comment] 2020-07-01 18:27
@psteckler Thanks, got past that error and managed to `make client_sdk` successfully but hit other dependency errors with `./scripts/compare_test_signatures.sh`. Is there an updated Docker toolchain image to make this easier as I've tried [this](https://github.com/CodaProtocol/coda/blob/develop/README-dev.md#toolchain-docker-image) but seemingly is outdated.

Anyway, I did build the module from the current [testnet commit](https://github.com/CodaProtocol/coda/commit/3e9b1748183e653a7891adea1fef07c8e1a7dfcd). I can successfully sign and verify messages with it i.e. this works:

```
import * as CodaSDK from "@garethtdavies/client-sdk";

let keys = CodaSDK.genKeys();
let signed = CodaSDK.signMessage("hello", keys);
if (CodaSDK.verifyMessage(signed)) {
    console.log("Message was verified successfully")
};
```

But trying to sign a payment using the below fails:

```
import * as CodaSDK from "@garethtdavies/client-sdk";

let keys = CodaSDK.genKeys();
let signedPayment = CodaSDK.signPayment({
    to: keys.publicKey,
    from: keys.publicKey,
    amount: 1000000000,
    fee: 1000000000,
    nonce: 0
  }, keys);
```

returns:

```
/home/runner/CodaPayment/node_modules/@garethtdavies/client-sdk/src/client_sdk.bc.js:196
a4A(a){if(a.length<24){for(var
            ^
TypeError: Cannot read property 'length' of undefined
    at a4A (/home/runner/CodaPayment/node_modules/@garethtdavies/client-sdk/src/client_sdk.bc.js:196:13)
    at bf (/home/runner/CodaPayment/node_modules/@garethtdavies/client-sdk/src/client_sdk.bc.js:857:9)
    at apH (/home/runner/CodaPayment/node_modules/@garethtdavies/client-sdk/src/client_sdk.bc.js:15450:27)
    at apI (/home/runner/CodaPayment/node_modules/@garethtdavies/client-sdk/src/client_sdk.bc.js:15451:3)
    at dha (/home/runner/CodaPayment/node_modules/@garethtdavies/client-sdk/src/client_sdk.bc.js:15561:23)
    at hD (/home/runner/CodaPayment/node_modules/@garethtdavies/client-sdk/src/client_sdk.bc.js:592:46)
    at Object.signPayment (/home/runner/CodaPayment/node_modules/@garethtdavies/client-sdk/src/client_sdk.bc.js:1037:32)
    at Object.signPayment (/home/runner/CodaPayment/node_modules/@garethtdavies/client-sdk/src/CodaSDK.bs.js:47:30)
    at index.ts:5:29
    at Script.runInThisContext (vm.js:122:20)
```

**Comment by psteckler** [comment] 2020-07-01 21:58
At the testnet commit, there's `signString`, not `signMessage`, and it takes a private key as the first argument. The method `signPayment` also takes a private key as the first argument. The second argument, of type `payment_js`, has a different format than your example.

Have you modified the code locally?

**Comment by garethtdavies** [comment] 2020-07-01 22:58
Not sure I am following this and I didn't modify the code locally. The docs for this commit indicate it's `signMessage` i.e. https://github.com/CodaProtocol/coda/tree/3e9b1748183e653a7891adea1fef07c8e1a7dfcd/frontend/client_sdk and https://github.com/CodaProtocol/coda/blob/3e9b1748183e653a7891adea1fef07c8e1a7dfcd/frontend/client_sdk/src/CodaSDK.d.ts#L48?

Anyway, after getting those example payment signatures working, I modified that and generated a transaction and submitted this on the current testnet and it worked 😄  So I guess, the issue is, as eluded earlier, the published npm version and its compatibility with the current testnet?

<img width="1173" alt="CleanShot 2020-07-01 at 15 57 03@2x" src="https://user-images.githubusercontent.com/135382/86298798-86016580-bbb3-11ea-9ba5-b643a0021898.png">

**Comment by psteckler** [comment] 2020-07-01 23:06
Oh, sorry, I was working directly with the Javascript compiland, and not the Typescript wrapper. I haven't used that, in fact, which is why I didn't recognize your examples.

So, we're all good? I can close the issue?

**Comment by garethtdavies** [comment] 2020-07-02 01:28
> So, we're all good? I can close the issue?

Maybe 😄. As it stands using the currently published NPM package https://www.npmjs.com/package/@o1labs/client-sdk it isn't possible to submit a transaction on the testnet as it results in a signature error. As for the root cause of that, I'm not sure as I couldn't make this work even publishing a package built from the current testnet release. I did manage to submit a tx above but not using the Typescript wrapper so maybe that's where the underlying issue lies?

**Comment by psteckler** [comment] 2020-07-02 02:06
I see, the successful txn was via Javascript.

I'll leave the issue open for now.

**Comment by bkase** [comment] 2020-07-02 18:57
@psteckler 

> If it's the testnet version, should updating the package be in the testnet release checklist?

Yes definitely, we should add this

**Comment by psteckler** [comment] 2020-07-07 17:54
@garethtdavies Brandon and I verified that the Typescript code was out-of-date wrt to the Javascript code. With a fix, signing payments works again from Typescript.

**Comment by bkase** [comment] 2020-07-07 21:00
@garethtdavies Published!

**Comment by garethtdavies** [comment] 2020-07-07 21:37
Awesome, thanks. Tested 0.1.3, and confirmed working.

**Comment by psteckler** [comment] 2020-07-07 22:16
Great, closing ...

**Closed by psteckler** 2020-07-07 22:16 UTC
Labels: testnet-bug
