### ISSUE TITLE
testnet-medium-curves: seed node doesn't start - rpc port doesn't open

### ISSUE THREAD

**Issue by jkrauska** [CodaProtocol/coda#2757] opened 2019-07-01 02:41 UTC
something seems to be broken with the medium-curves build.

starting daemon like this:
```
coda daemon -tracing -client-port 8301 -external-port 8302 -config-directory /home/admin/test-coda -external-ip 54.200.104.103 -rest-port 8304
```

It does some of the normal startup stuff:

```
{"timestamp":"2019-07-01 02:36:56.061767Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 159, characters 65-72"},"message":"error reading daemon.json: (Unix.Unix_error\\\"No such file or directory\\\"open\\\"((filename /home/admin/test-coda/daemon.json) (mode (O_RDONLY O_CLOEXEC)) (perm 0o0))\\\")","metadata":{"pid":2493}}
{"timestamp":"2019-07-01 02:36:56.061834Z","level":"Warn","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 161, characters 64-71"},"message":"failed to read daemon.json, not using it","metadata":{"pid":2493}}
{"timestamp":"2019-07-01 02:36:56.061849Z","level":"Info","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 182, characters 64-71"},"message":"didn't find snark-worker-fee in the config file, using default","metadata":{"pid":2493}}
{"timestamp":"2019-07-01 02:36:56.061859Z","level":"Info","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 182, characters 64-71"},"message":"didn't find max-concurrent-connections in the config file, using default","metadata":{"pid":2493}}
{"timestamp":"2019-07-01 02:36:56.061870Z","level":"Info","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 182, characters 64-71"},"message":"didn't find work-selection in the config file, using default","metadata":{"pid":2493}}
{"timestamp":"2019-07-01 02:36:56.061879Z","level":"Info","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 182, characters 64-71"},"message":"didn't find peers in the config file, using default","metadata":{"pid":2493}}
{"timestamp":"2019-07-01 02:36:56.073408Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 352, characters 54-61"},"message":"Creating trust_system at /home/admin/test-coda/trust","metadata":{"pid":2493}}
{"timestamp":"2019-07-01 02:37:03.006280Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 366, characters 63-70"},"message":"Creating consensus local state at /home/admin/test-coda/trust","metadata":{"pid":2493}}
{"timestamp":"2019-07-01 02:37:03.006465Z","level":"Warn","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 334, characters 62-69"},"message":"long async cycle 6.944053053s","metadata":{"pid":2493}}
{"timestamp":"2019-07-01 02:37:03.018641Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 389, characters 64-71"},"message":"Creating receipt_chain_database at /home/admin/test-coda/receipt_chain","metadata":{"pid":2493}}
{"timestamp":"2019-07-01 02:37:03.030911Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 397, characters 62-69"},"message":"Creating transaction_database at /home/admin/test-coda/transaction","metadata":{"pid":2493}}
{"timestamp":"2019-07-01 02:37:26.518717Z","level":"Info","source":{"module":"Coda_lib","location":"File \"lib/coda_lib/coda_lib.ml\", line 382, characters 32-39"},"message":"Persistence database does not exist yet. Creating it at /home/admin/test-coda/transition_frontier","metadata":{"pid":2493}}
{"timestamp":"2019-07-01 02:37:27.299611Z","level":"Warn","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 334, characters 62-69"},"message":"long async cycle 780.639813ms","metadata":{"pid":2493}}
{"timestamp":"2019-07-01 02:37:27.299922Z","level":"Debug","source":{"module":"Kademlia__Membership","location":"File \"lib/kademlia/membership.ml\", line 150, characters 56-63"},"message":"Args: (test 0.0.0.0 \\\"(\\\\\"54.200.104.103\\\\\", 8303)\\\")\n","metadata":{"pid":2493}}
{"timestamp":"2019-07-01 02:37:27.301045Z","level":"Info","source":{"module":"Transition_router","location":"File \"lib/transition_router/transition_router.ml\", line 75, characters 53-60"},"message":"Starting Transition Frontier Controller phase","metadata":{"pid":2493}}
{"timestamp":"2019-07-01 02:37:27.301188Z","level":"Debug","source":{"module":"Network_pool__Transaction_pool","location":"File \"lib/network_pool/transaction_pool.ml\", line 220, characters 69-76"},"message":"Got frontier!","metadata":{"pid":2493}}
{"timestamp":"2019-07-01 02:37:27.301527Z","level":"Debug","source":{"module":"Network_pool__Transaction_pool","location":"File \"lib/network_pool/transaction_pool.ml\", line 246, characters 69-76"},"message":"Re-validated transaction pool after restart: dropped 0 of 0 previously in pool","metadata":{"pid":2493}}
{"timestamp":"2019-07-01 02:37:27.301947Z","level":"Trace","source":{"module":"Network_pool__Transaction_pool","location":"File \"lib/network_pool/transaction_pool.ml\", line 134, characters 58-65"},"message":"Diff: removed: $removed added: $added from best tip","metadata":{"added":[],"pid":2493,"removed":[]}}
{"timestamp":"2019-07-01 02:37:27.302019Z","level":"Debug","source":{"module":"Network_pool__Transaction_pool","location":"File \"lib/network_pool/transaction_pool.ml\", line 177, characters 58-65"},"message":"Finished handling diff. Old pool size 0, new pool size 0. Dropped 0 commands during backtracking to maintain max size.","metadata":{"pid":2493}}
{"timestamp":"2019-07-01 02:37:27.303653Z","level":"Debug","source":{"module":"Kademlia__Membership","location":"File \"lib/kademlia/membership.ml\", line 250, characters 64-71"},"message":"Creating instance","metadata":{"pid":2493}}
{"timestamp":"2019-07-01 02:37:27.303680Z","level":"Debug","source":{"module":"Kademlia__Membership","location":"File \"lib/kademlia/membership.ml\", line 250, characters 64-71"},"message":"Dumping initial live peers","metadata":{"pid":2493}}
```

and then just stalls.

I let it sit for another 5min, and nothing happened.

CPU and RAM don't look out of the ordinary.

This is using the deb build from CI.
coda-testnet-postake-medium-curves 0.1.155577-CI

**Comment by jkrauska** [comment] 2019-07-01 02:45
to cross check, I downgraded to the older smaller curves image:

coda-testnet-postake          0.1.155565-CI

It starts the same, and then a minute after it moves on with "Checking for next proposal..."

I'm not seeing that come in on medium curves...

```
{"timestamp":"2019-07-01 02:42:36.099114Z","level":"Debug","source":{"module":"Kademlia__Membership","location":"File \"lib/kademlia/membership.ml\", line 250, characters 64-71"},"message":"Dumping initial live peers","metadata":{"pid":2756}}

...

{"timestamp":"2019-07-01 02:43:36.098237Z","level":"Info","source":{"module":"Consensus__Proof_of_stake","location":"File \"lib/consensus/proof_of_stake.ml\", line 2540, characters 53-60"},"message":"Checking for next proposal...","metadata":{"pid":2756}}
{"timestamp":"2019-07-01 02:43:36.098296Z","level":"Info","source":{"module":"Consensus__Proof_of_stake","location":"File \"lib/consensus/proof_of_stake.ml\", line 2553, characters 53-60"},"message":"systime: 1561949016098, epoch-slot@systime: 00003025-0087, starttime@epoch@systime: 1561946400000","metadata":{"pid":2756}}
{"timestamp":"2019-07-01 02:43:36.098310Z","level":"Info","source":{"module":"Consensus__Proof_of_stake","location":"File \"lib/consensus/proof_of_stake.ml\", line 2559, characters 55-62"},"message":"Selecting correct epoch data from state -- epoch by time: 3025, state epoch: 0, state epoch count: 0","metadata":{"pid":2756}}
{"timestamp":"2019-07-01 02:43:36.098429Z","level":"Info","source":{"module":"Consensus__Proof_of_stake","location":"File \"lib/consensus/proof_of_stake.ml\", line 2580, characters 57-64"},"message":"using curr_epoch_snapshot root hash 215559604601373068479131943327375543192000592250033567113675261773047323112613330340948225","metadata":{"pid":2756}}
{"timestamp":"2019-07-01 02:43:36.098448Z","level":"Info","source":{"module":"Consensus__Proof_of_stake","location":"File \"lib/consensus/proof_of_stake.ml\", line 2641, characters 57-64"},"message":"No slots won in this epoch. Waiting for next epoch, @1561950720000","metadata":{"pid":2756}}
{"timestamp":"2019-07-01 02:43:36.098471Z","level":"Info","source":{"module":"Web_pipe","location":"File \"app/cli/src/web_pipe.ml\", line 115, characters 57-64"},"message":"Not running a web client pipe","metadata":{"pid":2756}}
{"timestamp":"2019-07-01 02:43:36.098811Z","level":"Info","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 457, characters 56-63"},"message":"Running coda services","metadata":{"pid":2756}}
```

Just in case, I'm going to go back to the medium curves version and give it a LONG time.

**Comment by jkrauska** [comment] 2019-07-01 03:00
Aha-- yeah.

it just needed a LONG time
10m (2*slot)

```
{"timestamp":"2019-07-01 02:48:52.635460Z","level":"Debug","source":{"module":"Kademlia__Membership","location":"File \"lib/kademlia/membership.ml\", line 250, characters 64-71"},"message":"Dumping initial live peers","metadata":{"pid":3207}}


{"timestamp":"2019-07-01 02:58:52.633506Z","level":"Info","source":{"module":"Consensus__Proof_of_stake","location":"File \"lib/consensus/proof_of_stake.ml\", line 2540, characters 53-60"},"message":"Checking for next proposal...","metadata":{"pid":3207}}
```

so maybe not a bug?

**Comment by ghost-not-in-the-shell** [comment] 2019-07-01 22:49
This is not a bug. Because I intentionally blocked a buff of things (proposer, rpc port, etc) for 2 * slot time in one of the hack.

This would get better as soon as my PR gets landed inside which I undo that hack.

**Closed** 2019-07-12 22:05 UTC
Labels: area-testnet
