### ISSUE TITLE
Start Coda Error

### ISSUE THREAD

**Issue by veiodruida** [CodaProtocol/coda#5052] opened 2020-06-09 23:40 UTC
I tried to start Coda several times and it always returns this error that is attached

[coda_crash_report_2020-06-09_23-32-19.039838.tar.gz](https://github.com/CodaProtocol/coda/files/4755391/coda_crash_report_2020-06-09_23-32-19.039838.tar.gz)

**Comment by bkase** [comment] 2020-06-23 20:01
Thanks! Dupe of #5059

**Closed by bkase** 2020-06-23 20:01 UTC
Labels: testnet-bug
