### ISSUE TITLE
Coda daemon is crashed.

### ISSUE THREAD

**Issue by StarLI-Trapdoor** [CodaProtocol/coda#4055] opened 2019-12-11 04:44 UTC
The log is attached.

**Comment by StarLI-Trapdoor** [comment] 2019-12-11 04:45
[coda_crash_report_2019-12-11_03-34-19.248145.tar.gz](https://github.com/CodaProtocol/coda/files/3948479/coda_crash_report_2019-12-11_03-34-19.248145.tar.gz)

**Comment by gregbostrom** [comment] 2019-12-11 19:15
This looks like a duplicate of https://github.com/CodaProtocol/coda/issues/3949
From the coda_short.log
```
{"timestamp":"2019-12-11 03:34:15.603127Z","level":"Fatal","source":{"module":"Init__Coda_run","location":"File \"app/cli/src/init/coda_run.ml\", line 419, characters 56-63"},"message":"Unhandled top-level exception: $exn\nGenerating crash report","metadata":{"exn":"(monitor.ml.
Error\n  (\"writer buffer has data older than\" (maximum_age 2m)\n    
(beginning_of_buffer\n       \"\\190\\232<\\001\\000\\000\\000\\000\\001\\000\\000\\000\\000\\000\\000\\000\\000\\001\\000\\000\\000\\000\\000\\000\\000\\000\\001\\000\\000\\000\\000\\000\\000\\000\\000\\001\\000\\000\\000\\000\\000\\000\\000\\000\\001\\000\\000\\000\\000\\000\\000\\000\\000\\001\\000\\000\\000\\000\\000\\000\\000\\000\\001\\000\\000\\000\\000\\000\\000\\000\\000\\001\\000\\000\\000\\000\\000\\000\\000\\000\\001\\000\\000\\000\\000\\000\\000\\000\\000\\001\\000\\000\\000\\000\\000\\000\\000\\000\\001\\000\\000\\000\\000\\000\\000\\000\\000\\001\\000\\000\\000\\000\\000\\000\\000\\000ry\\001\\027get_bootstrappable_best_tip\\001\\012get_ancestry\\001\\026get_transition_chain_proof\\001\\020get_transition_chain\\001\\\n      \\nban_notify\\001\\016get_epoch_ledger\\001\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\")\n    (writer\n      ((id 18934)\n        (fd\n          ((file_descr 54)\n            (info\n              (socket\n                ((listening_on\n                   ((type_ ((family PF_INET) (socket_type SOCK_STREAM)))\n                     (fd\n                       ((file_descr 48)\n                         (info\n                           (replaced\n                             (listening\n                               (previously_was\n                                 (replaced\n                                   ((socket (bound_on 0.0.0.0:8302))\n                                     (previously_was\n                                       (socket\n                                         ((family PF_INET)\n                                           (socket_type SOCK_STREAM))))))))))\n                         (kind (Socket Passive)) (supports_nonblock true)\n                         (have_set_nonblock true) (state (Open Empty))\n                         (watching\n                           ((read (Watch_once Empty)) (write Not_watching)))\n                         (watching_has_changed false) (num_active_syscalls 1)\n                         (close_finished Empty)))))\n                  (client 144.91.110.204:33835))))\n            (kind (Socket Active)) (supports_nonblock true)\n            (have_set_nonblock true) (state (Open Empty))\n            (watching ((read (Watch_once Empty)) (write (Watch_once Empty))))\n            (watching_has_changed false) (num_active_syscalls 2)\n            (close_finished Empty)))\n        (monitor\n          (((name (id 270794)) (here ()) (id 270794) (has_seen_error false)\n             (is_detached true))\n            ((name coda) (here ()) (id 9) (has_seen_error false)\n              (is_detached true))\n            ((name \"\") (here ()) (id 2) (has_seen_error false)\n              (is_detached true))))\n        (inner_monitor\n          (((name (id 270795)) (here ()) (id 270795) (has_seen_error false)\n             (is_detached true))\n            ((name coda) (here ()) (id 9) (has_seen_error false)\n              (is_detached true))\n            ((name \"\") (here ()) (id 2) (has_seen_error false)\n              (is_detached true))))\n        (background_writer_state Running) (background_writer_stopped Empty)\n        (syscall Per_cycle) (bytes_received 20769340)\n        (bytes_written 12001290) (scheduled_bytes 8768050)\n        (scheduled_back 116) (back 116) (close_state Open)\n        (close_finished Empty) (close_started Empty)\n        (num_producers_to_flush_at_close 0)\n        (flush_at_shutdown_elt (<opaque>))\n        (check_buffer_age\n          (((writer <opaque>) (maximum_age 2m)\n             (bytes_received_at_now_minus_maximum_age 20769232)\n             (bytes_received_queue\n               (20769241 20769250 20769259 20769268 20769277 20769286\n                 20769295 20769304 20769313 20769322 20769331 20769340))\n             (times_received_queue\n               ((2019-12-10 22:32:20.543894708-05:00)\n                 (2019-12-10 22:32:30.544947214-05:00)\n                 (2019-12-10 22:32:40.592274296-05:00)\n                 (2019-12-10 22:32:50.593331694-05:00)\n                 (2019-12-10 22:33:00.594240344-05:00)\n                 (2019-12-10 22:33:10.595172160-05:00)\n                 (2019-12-10 22:33:20.596246906-05:00)\n                 (2019-12-10 22:33:30.597275624-05:00)\n                 (2019-12-10 22:33:40.598075525-05:00)\n                 (2019-12-10 22:33:50.599121262-05:00)\n                 (2019-12-10 22:34:00.600197623-05:00)\n                 (2019-12-10 22:34:10.601383294-05:00)))\n             (bytes_seen 20769340) (too_old (Full ())))))\n        (consumer_left Empty) (raise_when_consumer_leaves false)\n        (open_flags (Full (Ok (rdwr)))) (line_ending Unix))))\n  (\"Caught by monitor (id 270794)\"))","pid":11067}}
```

**Comment by bkase** [comment] 2019-12-19 00:39
Thanks for the report, deduping in favor of #3949

**Closed by bkase** 2019-12-19 00:39 UTC
Labels: bug
