### ISSUE TITLE
[CRASH] monitor.ml.Error "Assert_failure lib/network_pool/indexed_pool.ml:529:8"

### ISSUE THREAD

**Issue by pavrych** [CodaProtocol/coda#4099] opened 2019-12-17 17:10 UTC
Generating crash report
        exn: "(monitor.ml.Error \"Assert_failure lib/network_pool/indexed_pool.ml:529:8\"\n  (\"Raised at file \\\"lib/network_pool/indexed_pool.ml\\\", line 529, characters 8-69\"\n    \"Called from file \\\"lib/network_pool/transaction_pool.ml\\\", line 534, characters 30-193\"\n    \"Called from file \\\"lib/network_pool/network_pool_base.ml\\\", line 26, characters 15-65\"\n    \"Called from file \\\"src/pipe.ml\\\", line 827, characters 4-56\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"\n    \"Caught by monitor coda\"))"

**Comment by yourbuddyconner** [comment] 2019-12-18 21:05
Seeing this on the graphql-proxy node as well: 

```
Command: "Command: (coda daemon -log-level Info -config-directory ~/.coda-config -client-port
 8301 -rest-port 8304 -external-port 10501 -discovery-port 10502
 -metrics-port 10000 -archive -peer
 /dns4/peer1-rising-phoenix.o1test.net/tcp/8303/ipfs/12D3KooWHMmfuS9DmmK9eH4GC31arDhbtHEBQzX6PwPtQftxzwJs
 -peer
 /dns4/peer2-rising-phoenix.o1test.net/tcp/8303/ipfs/12D3KooWAux9MAW1yAdD8gsDbYHmgVjRvdfYkpkfX7AnyGvQaRPF
 -peer
 /dns4/peer3-rising-phoenix.o1test.net/tcp/8303/ipfs/12D3KooWCZA4pPWmDAkQf6riDQ3XMRN5k99tCsiRhBAPZCkA8re7)"   
  Exception: "(monitor.ml.Error "Assert_failure lib/network_pool/indexed_pool.ml:529:8"
  ("Raised at file \"lib/network_pool/indexed_pool.ml\", line 529, characters 8-69"
    "Called from file \"lib/network_pool/transaction_pool.ml\", line 534, characters 30-193"
    "Called from file \"lib/network_pool/network_pool_base.ml\", line 26, characters 15-65"
    "Called from file \"src/pipe.ml\", line 827, characters 4-56"
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5"
    "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
    "Caught by monitor coda"))"   
  Machine: "x86_64"   
  OS_type: "Unix"   
  Release: "4.14.138+"   
  Sys_name: "Linux" 
```

**Comment by bkase** [comment] 2019-12-19 00:30
Dupe of #3644

**Comment by bkase** [comment] 2019-12-19 00:31
Thanks for reporting!

**Closed by bkase** 2019-12-19 00:30 UTC

**Comment by bkase** [comment] 2019-12-19 00:36
Actually let's dedupe with #4066

**Comment by ghost-not-in-the-shell** [comment] 2020-02-01 00:42
After some investigating, I think this bug is mainly caused by an async race condition in transaction_pool.

There are two separate processes trying to update the transaction pool object in two different ways. Specifically,
1. every transaction_pool_diff that comes from the network would trigger an update for the pool through `Resource_pool.Diff.apply` function
2. every best_tip_diff that comes from the transition frontier system would also trigger a different  update for the pool through `handle_diff` function

If `apply` overwrite the result of `handle_diff` then there are chances the system would die with the above bug.

--------
There's  another possible reason for this bug:
Because the assertion would take a look at the nonce at best_tip_ledger, and best_tip_ledger is updated when a best_tip_diff arrives, and best_tip_ledger and best_tip_diff could be mismatch due to the desynchronization nature of the transition frontier extensions. I think this https://github.com/CodaProtocol/coda/issues/4157 would fix it.
