### ISSUE TITLE
Prove-payment on other nodes than the one where it is created

### ISSUE THREAD

**Issue by Mixa84** [CodaProtocol/coda#1853] opened 2019-03-13 09:50 UTC
In a setup of 3 nodes (seed,proposer and snarker) when you do send-payment and the tx is proved, you can only do prove-payment only on node where it is sent. If you try to prove-payment on other nodes it returns error ' Cannot retrieve receipt: 283713616829740749355249742121805740607312826754415751254176186576877442434116369403281535`

**Comment by enolan** [comment] 2019-04-03 18:32
So this is actually by design, nodes don't keep a full database of all payments so that the state can be a constant size. You are able to prove a payment only on a node that recorded it, but you can verify it on any node. Nodes record only payments they originally sent. I made a ticket to add an option to keep a full database at #2123. The verification command was actually missing from the CLI though, I fixed that in #2124 which should be merged soon. Here's the workflow for proving and verifying a payment. It's pretty clunky, but should be better in the future.

* send a payment and record the receipt chain hash it tells you
* run `coda client prove-payment -address $SENDER_PUBLIC_KEY -receipt-chain-hash $HASH` on the node that you sent the payment from and record the JSON output in a file
* take the payment out of that file and put it in a separate one. It'll be in the list with key `payments`. You can copy paste or use `jq` with the filter `.payments | .[0]` to extract the first payment in the list
* on the other node, after #2124 lands, run `coda client verify-payment -address $SENDER_PUBLIC_KEY -payment-path $PAYMENT_JSON_FILE -proof-path $PROOF_JSON_FILE`. If everything went well you should get "Payment is valid on the existing blockchain!"

**Closed by enolan** 2019-04-03 18:32 UTC
