### ISSUE TITLE
Coda Daemon crashed

### ISSUE THREAD

**Issue by etekis** [CodaProtocol/coda#2980] opened 2019-07-25 00:13 UTC
Wasn't attending to the daemon or using the client. Locked my laptop. When I came back it had crashed. 

{"timestamp":"2019-07-24 23:58:24.674328Z","level":"Debug","source":{"module":"Consensus__Proof_of_stake","location":"File \"src/lib/consensus/proof_of_stake.ml\", line 24$
{"timestamp":"2019-07-24 23:58:24.674482Z","level":"Debug","source":{"module":"Consensus__Proof_of_stake","location":"File \"src/lib/consensus/proof_of_stake.ml\", line 24$
{"timestamp":"2019-07-24 23:58:24.679252Z","level":"Debug","source":{"module":"Consensus__Proof_of_stake","location":"File \"src/lib/consensus/proof_of_stake.ml\", line 24$
{"timestamp":"2019-07-24 23:58:24.679340Z","level":"Debug","source":{"module":"Consensus__Proof_of_stake","location":"File \"src/lib/consensus/proof_of_stake.ml\", line 24$
{"timestamp":"2019-07-24 23:58:24.682528Z","level":"Debug","source":{"module":"Trust_system__Peer_trust","location":"File \"src/lib/trust_system/peer_trust.ml\", line 118,$
{"timestamp":"2019-07-24 23:58:24.687533Z","level":"Debug","source":{"module":"Consensus__Proof_of_stake","location":"File \"src/lib/consensus/proof_of_stake.ml\", line 24$
{"timestamp":"2019-07-24 23:58:24.687618Z","level":"Debug","source":{"module":"Consensus__Proof_of_stake","location":"File \"src/lib/consensus/proof_of_stake.ml\", line 24$
{"timestamp":"2019-07-24 23:58:24.776416Z","level":"Debug","source":{"module":"Trust_system__Peer_trust","location":"File \"src/lib/trust_system/peer_trust.ml\", line 118,$
{"timestamp":"2019-07-24 23:58:25.464844Z","level":"Debug","source":{"module":"Staged_ledger","location":"File \"src/lib/staged_ledger/staged_ledger.ml\", line 784, charac$
{"timestamp":"2019-07-24 23:58:25.485034Z","level":"Debug","source":{"module":"Consensus__Proof_of_stake","location":"File \"src/lib/consensus/proof_of_stake.ml\", line 24$
{"timestamp":"2019-07-24 23:58:25.485122Z","level":"Debug","source":{"module":"Consensus__Proof_of_stake","location":"File \"src/lib/consensus/proof_of_stake.ml\", line 24$
{"timestamp":"2019-07-24 23:58:25.488969Z","level":"Debug","source":{"module":"Consensus__Proof_of_stake","location":"File \"src/lib/consensus/proof_of_stake.ml\", line 24$
{"timestamp":"2019-07-24 23:58:25.489027Z","level":"Debug","source":{"module":"Consensus__Proof_of_stake","location":"File \"src/lib/consensus/proof_of_stake.ml\", line 24$
{"timestamp":"2019-07-24 23:58:25.490838Z","level":"Trace","source":{"module":"Transition_frontier","location":"File \"src/lib/transition_frontier/transition_frontier.ml\"$
{"timestamp":"2019-07-24 23:58:25.493937Z","level":"Debug","source":{"module":"Transition_frontier","location":"File \"src/lib/transition_frontier/transition_frontier.ml\"$
{"timestamp":"2019-07-24 23:58:25.493986Z","level":"Debug","source":{"module":"Transition_frontier","location":"File \"src/lib/transition_frontier/transition_frontier.ml\"$
{"timestamp":"2019-07-24 23:58:25.496545Z","level":"Trace","source":{"module":"Transition_frontier","location":"File \"src/lib/transition_frontier/transition_frontier.ml\"$
{"timestamp":"2019-07-24 23:58:25.497146Z","level":"Debug","source":{"module":"Coda_run","location":"File \"src/app/cli/src/coda_run.ml\", line 70, characters 52-59"},"mes$
{"timestamp":"2019-07-24 23:58:25.579272Z","level":"Debug","source":{"module":"Transition_frontier","location":"File \"src/lib/transition_frontier/transition_frontier.ml\"$
{"timestamp":"2019-07-24 23:58:25.595792Z","level":"Debug","source":{"module":"Coda_run","location":"File \"src/app/cli/src/coda_run.ml\", line 80, characters 58-65"},"mes$

(monitor.ml.Error
  (Failure
    "Couldn't unregister mask with UUID c9ee5d35-7b5b-3b21-2824-c3c633dfd1af from parent a78dbbfa-6fad-37cb-2fad-f193aafed35c, mask not registered with that parent")
  ("Raised at file \"stdlib.ml\", line 33, characters 17-33"
    "Called from file \"src/lib/merkle_mask/maskable_merkle_tree.ml\", line 159, characters 12-72"
    "Called from file \"src/lib/coda_base/ledger.ml\" (inlined), line 167, characters 35-79"
    "Called from file \"src/lib/transition_frontier/transition_frontier.ml\", line 784, characters 24-63"
    "Called from file \"src/lib/transition_frontier/transition_frontier.ml\", line 787, characters 14-35"
    "Called from file \"list.ml\", line 106, characters 12-15"
    "Called from file \"src/list0.ml\" (inlined), line 26, characters 40-75"
    "Called from file \"src/lib/transition_frontier/transition_frontier.ml\", line 803, characters 12-66"
    "Called from file \"src/lib/transition_handler/processor.ml\", line 64, characters 17-51"
    "Called from file \"src/lib/transition_handler/processor.ml\", line 149, characters 8-129"
    "Called from file \"src/deferred0.ml\", line 56, characters 64-69"
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5"
    "Called from file \"src/job_queue.ml\", line 170, characters 6-47"
    "Caught by monitor coda"))

**Comment by mrmr1993** [comment] 2019-07-25 15:03
Repro'd with similar failure:

```
{"timestamp":"2019-07-25 14:53:39.014881Z","level":"Debug","source":{"module":"Transition_frontier","location":"File \"lib/transition_frontier/transition_frontier.ml\", line 737, characters 60-67"},"message":"added 1 breadcrumbs and removed 0 making path to new best tip","metadata":{"new_breadcrumbs":[{"transition_with_hash":{"data":{"protocol_state":{"previous_state_hash":"11329938411939381402404298706162238437716195165094404519198661108490304139184012038995015782526491269717029429793375065549555496448808681289966641916942453470408090449733054190031520454280827227376470171943979915116003900781414","body":{"blockchain_state":{"staged_ledger_hash":{"non_snark":{"ledger_hash":"19286989662194042827533889819599870975819992891950845836709364980725409512250901108525030785629841935158198400851281805471241758205388801803579505924423781293340905634732303223816801941509279740972291635081630398007015292354676","aux_hash":"8iqpLDF7c92jEzYneJYJjNyDe2ZQJcYFweMtaCe3Xf9QaQzGPTyxV","pending_coinbase_aux":"5MNeNqTPqKPUqCQwrU7tLGVFUYzviH6GjCPT228uw87g1FTR2dA"},"pending_coinbase_hash":"34659698052279930310956170377372694176608458243222522254138325910814883157219824154287417047643071372364097060881782033965065661757841860379405208713136153355445389877837660092515501569521489439068297670114517812836642541395305"},"snarked_ledger_hash":"16614876361025011603230697695085370554301275323584479787590866411302392047573659534418116050177771442629407029327750673002858692494540135237949546362363166695549101792654595707467823915385172461099965870109734933066241071519040","timestamp":"1564066201522"},"consensus_state":{"blockchain_length":"397","epoch_count":"6","min_epoch_length":"62","last_vrf_output":"8H7DcZaXMvRY6hVViiyBCa2rDXu2YaV49ekJmYQXLB6QajrNhn","total_currency":10114280,"curr_epoch":"6","curr_slot":"4","staking_epoch_data":{"ledger":{"hash":"16614876361025011603230697695085370554301275323584479787590866411302392047573659534418116050177771442629407029327750673002858692494540135237949546362363166695549101792654595707467823915385172461099965870109734933066241071519040","total_currency":10114280},"seed":"36713587514898153795081577044342906299359651617051762021547489175678034613480024546086421245128390412210286606170183859615174751170303093099912269414594528164240669608486122055927429218369857960576767361879411367195116040465735","start_checkpoint":"26397546725798828302303363561457531545785216820231651548995049516711592732562755478989820181523748891871716831360575604174223468165368908073311698624444681057227841063960097562595868603272409646610641708943469655922611274611941","lock_checkpoint":"37222162346680766138848064039017266989516649585161096877415560975317815933550776162509362428188221319850504134047604915336104004176210961349078012277158976311703409913043167670202746614830353115489167560125790949422065818865375","epoch_length":"67"},"next_epoch_data":{"ledger":{"hash":"16614876361025011603230697695085370554301275323584479787590866411302392047573659534418116050177771442629407029327750673002858692494540135237949546362363166695549101792654595707467823915385172461099965870109734933066241071519040","total_currency":10114280},"seed":"2071893303198007985737678972190309212568452221625132024511988170095494148670997278812694070338313361389889122280160253462982652030041813566301365289695187505618174204273471887226695702458395861269694368663558765191107385382142","start_checkpoint":"39400081402700801099461373041848191661358937821974557536101841741030611341824624144050504330730326428257692352942377860767671268903324610900469867109867963855590321947919345915212472616661053107625632113021893444564454929692765","lock_checkpoint":null,"epoch_length":"5"},"has_ancestor_in_same_checkpoint_window":true,"checkpoints":{"data":{"prefix":["36782869935965414222803766111589106059928653266006562368237491770920419223196351921290099024431045678696270371899077719754582744324683342090263286949885333652891185465016898405769609259698781267121722885844488370666255009246289"],"tail":"0"},"hash":"12062717558525538699047780862059193266924556459560851006160860343216576123787521205271672413556467062262639340546367611173236998289502441061812779352640732323492364704217327960088370937391626808596131208187008001457662385788416"}}}},"protocol_state_proof":"<opaque>","staged_ledger_diff":"<opaque>"},"hash":"34251449828471870973593909212998750432405939954402262411160861206924539872387862636375792461488265987470683940951185034516753040281938647341079148945502052438109682432705600370120548169396749702611569617031861730701530975860267"},"staged_ledger":"<opaque>","just_emitted_a_proof":false}],"old_breadcrumbs":[],"pid":6524}}
{"timestamp":"2019-07-25 14:53:39.014964Z","level":"Debug","source":{"module":"Transition_frontier","location":"File \"lib/transition_frontier/transition_frontier.ml\", line 753, characters 64-71"},"message":"Moving the root of the transition frontier. The new node is $distance_to_root blocks after the root, which exceeds the max length of $max_length.","metadata":{"distance_to_parent":4,"max_length":3,"pid":6524}}
{"timestamp":"2019-07-25 14:53:39.015517Z","level":"Trace","source":{"module":"Transition_frontier","location":"File \"lib/transition_frontier/transition_frontier.ml\", line 790, characters 64-71"},"message":"Removing $length_of_garbage nodes because the old root is one of their ancestors and we're deleting it","metadata":{"all_garbage":["16836936930699610944287441503016673819938459942633357374154667348341684615723196549026974296436788528910707855150941693204335441087900061320289998311815253175198652663275075410639076926192372266941497232782593480296831873334759"],"garbage_direct_descendants":["16836936930699610944287441503016673819938459942633357374154667348341684615723196549026974296436788528910707855150941693204335441087900061320289998311815253175198652663275075410639076926192372266941497232782593480296831873334759"],"length_of_garbage":1,"local_state":{"staking_epoch_snapshot":{"ledger_hash":"16614876361025011603230697695085370554301275323584479787590866411302392047573659534418116050177771442629407029327750673002858692494540135237949546362363166695549101792654595707467823915385172461099965870109734933066241071519040","delegators":{}},"next_epoch_snapshot":{"ledger_hash":"16614876361025011603230697695085370554301275323584479787590866411302392047573659534418116050177771442629407029327750673002858692494540135237949546362363166695549101792654595707467823915385172461099965870109734933066241071519040","delegators":{}},"last_checked_slot_and_epoch":{},"genesis_epoch_snapshot":{"ledger_hash":"38932695040467596106866402734597443669063381446628167838929129222958650359402660018169492542114228579857016809663362878702967691140114883880635297843337526424344049903879831696969707777320618038873222528382381697025453708056747","delegators":{}}},"pid":6524}}
{"timestamp":"2019-07-25 14:53:39.015618Z","level":"Debug","source":{"module":"Coda_run","location":"File \"app/cli/src/coda_run.ml\", line 70, characters 52-59"},"message":"Successfully wrote the visualization of the registered masks at location: /home/matthew/.coda-config/registered_masks.dot.","metadata":{"coda_run":"Logging state before program ends","pid":6524}}
{"timestamp":"2019-07-25 14:53:39.061767Z","level":"Debug","source":{"module":"Coda_run","location":"File \"app/cli/src/coda_run.ml\", line 80, characters 58-65"},"message":"Successfully wrote the visualization of the transition frontier at location: /home/matthew/.coda-config/frontier.dot.","metadata":{"coda_run":"Logging state before program ends","pid":6524}}


  ☠  Coda Daemon crashed. The Coda Protocol developers would like to know why!

  Please:
    Open an issue:
      https://github.com/CodaProtocol/coda/issues/new

    Briefly describe what you were doing, and include the last 20 lines from .coda-config/coda.log.
    And then paste the following:

    (monitor.ml.Error
  (Failure
    "Couldn't unregister mask with UUID 720f08a0-3ead-3423-7603-dd90f15edd1a from parent bdc8211a-16d6-3543-77c5-510b265204cf, mask not registered with that parent")
  ("Raised at file \"stdlib.ml\", line 33, characters 17-33"
    "Called from file \"lib/merkle_mask/maskable_merkle_tree.ml\", line 159, characters 12-72"
    "Called from file \"lib/coda_base/ledger.ml\" (inlined), line 167, characters 35-79"
    "Called from file \"lib/transition_frontier/transition_frontier.ml\", line 784, characters 24-63"
    "Called from file \"lib/transition_frontier/transition_frontier.ml\", line 787, characters 14-35"
    "Called from file \"list.ml\", line 106, characters 12-15"
    "Called from file \"src/list0.ml\" (inlined), line 26, characters 40-75"
    "Called from file \"lib/transition_frontier/transition_frontier.ml\", line 803, characters 12-66"
    "Called from file \"lib/transition_handler/processor.ml\", line 64, characters 17-51"
    "Called from file \"lib/transition_handler/processor.ml\", line 149, characters 8-129"
    "Called from file \"src/deferred0.ml\", line 56, characters 64-69"
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5"
    "Called from file \"src/job_queue.ml\", line 170, characters 6-47"
    "Caught by monitor coda"))
```

I'll keep a copy of the full log (`coda-1564065375.log`) in case it's useful.

**Comment by enolan** [comment] 2019-07-26 00:15
closing as duplicate of #2969

**Closed by enolan** 2019-07-26 00:15 UTC
