### ISSUE TITLE
Crash else 

### ISSUE THREAD

**Issue by Igor-Tselkovskiy** [CodaProtocol/coda#4080] opened 2019-12-13 20:01 UTC
error: "(src/connection.ml.Handshake_error.Handshake_error\n (Timeout (\"Client connected via TCP\" (134.209.49.152 8302))))"
2019-12-13 19:28:58 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
	exn: "(monitor.ml.Error \"Assert_failure lib/network_pool/indexed_pool.ml:529:8\"\n  (\"Raised at file \\\"lib/network_pool/indexed_pool.ml\\\", line 529, characters 8-69\"\n    \"Called from file \\\"lib/network_pool/transaction_pool.ml\\\", line 534, characters 30-193\"\n    \"Called from file \\\"lib/network_pool/network_pool_base.ml\\\", line 26, characters 15-65\"\n    \"Called from file \\\"src/pipe.ml\\\", line 827, characters 4-56\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"\n    \"Caught by monitor coda\"))"

**Comment by Igor-Tselkovskiy** [comment] 2019-12-13 20:02
[coda_crash_report_2019-12-13_19-28-58.227148.tar.gz](https://github.com/CodaProtocol/coda/files/3962508/coda_crash_report_2019-12-13_19-28-58.227148.tar.gz)

**Comment by bkase** [comment] 2019-12-19 00:32
Dupe of #3644 ; thanks for reporting!

**Closed by bkase** 2019-12-19 00:32 UTC

**Comment by bkase** [comment] 2019-12-19 00:36
Actually lets dedupe with #4066
