### ISSUE TITLE
Coda Daemon crashed after doing ledger catchup.

### ISSUE THREAD

**Issue by aquariusluo** [CodaProtocol/coda#5136] opened 2020-06-16 02:27 UTC
[coda.log](https://github.com/CodaProtocol/coda/files/4783997/coda.log)

Coda daemon crashed when restart with "coda daemon -peer $SEED1 -peer $SEED2" after doing ledger catchup.
[error.log](https://github.com/CodaProtocol/coda/files/4784163/error.log)

**Comment by bkase** [comment] 2020-06-16 20:17
```
	exn: "(monitor.ml.Error\n  \"Assert_failure src/lib/block_producer/block_producer.ml:598:16\"\n  (\"Raised at file \\\"src/lib/block_producer/block_producer.ml\\\", line 598, characters 16-234\"\n    \"Called from file \\\"src/result.ml\\\", line 151, characters 9-15\"\n    \"Caught by monitor coda\"))"
2020-06-16 02:12:58 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
	exn: "(monitor.ml.Error\n  (Failure\n    \"traced task `R&check next block timing` failed, exception reported to parent monitor\")\n  (\"Raised at file \\\"stdlib.ml\\\", line 33, characters 17-33\"\n    \"Called from file \\\"src/deferred1.ml\\\", line 17, characters 40-45\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"\n    \"Caught by monitor coda\"))"
```

**Comment by bkase** [comment] 2020-06-16 20:18
This seems to be a duplicate of the `required_local_state` bug #5079

**Comment by bkase** [comment] 2020-06-16 20:18
Thanks for sharing!

**Closed by bkase** 2020-06-16 20:18 UTC
