### ISSUE TITLE
Coda in crash loop after switching to -block-producer-key

### ISSUE THREAD

**Issue by k** [CodaProtocol/coda#5120] opened 2020-06-13 11:24 UTC
Coda was working properly when I imported the account, it was submitting snark work and producing blocks.

However, I wanted to try running multiple nodes, after trying this I found out from @garethtdavies in Discord that it would cause problems for the same key. Therefore I reverted this change and went back to a single snark worker and block producer.

It was crashing, so I reset the state of my node entirely to have a clean state and redeployed it. Now the only change left from the original node was `-block-producer-key /root/privkey` instead of `-block-producer-pubkey $PUBKEY`.

Now it starts up but eventually crashes.

There are lots of log lines like the following:
```
2020-06-13 01:22:35 UTC [Error] Unconsumed item in cache: $cache
cache: "cached item was not consumed (cache name = \"Transition_handler__Unprocessed_transition_cache\")"
```

Summary:
```json
{"num_accounts":10040,"blockchain_length":663,"highest_block_length_received":692,"uptime_secs":473,"ledger_merkle_root":"4mKBT3x3H3u89Hsqe1nWD3dh3sWAPaPfUdZNiwAWXALKBbztdv3dghRSqourLN5KrYFPYhgazsybArJwFg3uDTwweFUjY7xgT96QLjApJF6McVuH36GWU8zeHRKXW41e2siPjGMSK5gjGcLBfBuE2vKVnKy3Sk93TjXG19o2WVJrEK8LjEirTB8N3Z5zo6zhCatqifujyT84zcfQgVv2v2XETm3NnivyBfj2DR6FLUcqD5D6V6YT9e8NjZHdjN7dotquA4RNipXC7tw8G2GDLdkAMs94QqBMran2FcxVo88uZjeSJqNVo17eDWcjBvFHSN","state_hash":"D2rcXVQbeXrzRyfTHPncq91vbTPSfkZuj15wC7LTqA1UkFX7KqS985SNvUp2SG72nE9uQsNrMfYxhASRCoSHpKkgpEskwdi57fTQvRgdpG2V476tA2THE1F33Mqu9kvoc334ieAd3o57WKXKc3YjvWNftq4XkfcczMftpwPp89WNYzqV1q1DzuVHDiha12VKat66Fn6cfUz37BvdkzrXPdoobARAXarq5gU9NG4Q1MMput8og6t2s3b4WgwsMCF3q4i7ANyvABfTZipEKNoJ2w7AyM7pBrrp8mBUmtNwzkVMoEphLt1spmxyNxzfjrBap5","commit_id":"3e9b1748183e653a7891adea1fef07c8e1a7dfcd","conf_dir":"/root/.coda-config","peers":["178.140.11.249:8302","62.171.189.96:8302","51.158.184.48:8302","122.115.61.107:8302","206.189.18.180:8302","140.238.210.230:8302","195.154.107.184:8302","142.93.149.94:8302","50.116.46.176:8302","165.227.27.76:8302","104.251.217.225:8302","157.245.226.150:8302","85.112.96.18:8302","62.171.157.25:8302","52.146.39.177:8302","34.107.51.14:8302","95.217.193.177:8302","76.126.180.198:62943","152.32.187.189:8302","13.126.180.163:8302","34.67.68.90:8302","161.97.67.178:8302","135.181.27.73:8302","167.99.111.179:8302","167.86.111.215:8302","34.74.183.100:10001","35.196.202.161:10002","35.222.209.138:8302","116.202.216.248:8302","172.104.230.180:8302","3.17.37.61:8302","78.46.43.210:8302","3.13.202.98:8302","173.249.38.94:8302","144.91.82.21:8302","52.186.151.174:8302","34.105.28.208:8302","107.152.47.24:8302","144.91.127.224:8302","162.245.23.134:34959","35.204.13.108:8302","95.216.219.132:8302","46.232.251.117:8302","173.254.205.202:8302","167.172.192.173:8302","95.217.204.49:8302","40.69.86.64:8302","46.232.251.94:8302","35.231.128.243:10001","95.216.152.25:8302","34.64.72.61:8302","167.99.85.10:8302","161.35.93.158:8302","34.74.83.1:10909","86.154.249.188:8302","167.172.203.143:8302","49.12.66.5:8302","161.97.64.10:8302","109.234.159.18:8302","95.217.197.116:8302","95.216.192.84:8302","49.12.14.80:8302","87.26.237.237:8302","35.246.224.149:8302","18.222.186.77:8302","148.251.91.50:8302","95.165.167.193:8302","144.64.184.15:48064","54.39.133.124:8302","159.89.127.140:8302","155.138.141.129:8302","159.89.155.126:8302","107.152.38.216:8302","159.89.84.150:8302","96.44.147.131:3092","76.186.208.37:8304","137.220.54.11:8302","162.212.158.152:8302","78.193.188.67:8302","34.82.5.66:8302","40.89.178.121:8302","76.186.208.37:8302","18.217.88.55:8302","206.180.245.231:8302","142.93.32.97:8302","34.91.73.182:8302","35.199.169.8:8302","95.217.203.62:8302","35.239.173.164:8302","139.162.132.135:8302","82.69.152.196:8302","51.15.246.57:8302","95.111.251.106:8302","62.171.139.102:8302","161.35.225.21:8302","52.203.46.42:8302","142.44.139.163:8302","62.171.153.4:8302","52.202.82.43:8302","95.217.197.115:8302"],"user_commands_sent":0,"snark_worker":"4vsRCVbWUyT9Zuh2U3YZtAYq1V6xwWWhBfuDU9ymJFJsCddQSsAzHoexMmqsecrRLiVoafy5aA1wS8DCRYh2yd97wfe9jZV5HnYt4tCADk9Qq4yAr7Fxu6UcqDFyaq8Q28unt9FrrntVL2wy","snark_work_fee":1,"sync_status":"Catchup","block_production_keys":["4vsRCVbWUyT9Zuh2U3YZtAYq1V6xwWWhBfuDU9ymJFJsCddQSsAzHoexMmqsecrRLiVoafy5aA1wS8DCRYh2yd97wfe9jZV5HnYt4tCADk9Qq4yAr7Fxu6UcqDFyaq8Q28unt9FrrntVL2wy"],"histograms":{"rpc_timings":{"get_staged_ledger_aux":{"dispatch":null,"impl":null},"answer_sync_ledger_query":{"dispatch":null,"impl":null},"get_ancestry":{"dispatch":null,"impl":null},"get_transition_chain_proof":{"dispatch":{"values":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"intervals":[[1000.0000000000086,1136.4832126482186],[1136.4832126482186,1291.5940926312048],[1291.5940926312048,1467.8750038309608],[1467.8750038309608,1668.2153001198121],[1668.2153001198121,1895.89868366906],[1895.89868366906,2154.6570268717232],[2154.6570268717232,2448.7315400542157],[2448.7315400542157,2782.942287553811],[2782.942287553811,3162.7671915737074],[3162.7671915737074,3594.4318187380427],[3594.4318187380427,4085.011421004358],[4085.011421004358,4642.546903447653],[4642.546903447653,5276.176619700187],[5276.176619700187,5996.28615525624],[5996.28615525624,6814.6785536835805],[6814.6785536835805,7744.767775855172],[7744.767775855172,8801.798563118215],[8801.798563118215,10003.096308094968],[10003.096308094968,11368.351028653215],[11368.351028653215,12919.940099556361],[12919.940099556361,14683.295031566244],[14683.295031566244,16687.31830973587],[16687.31830973587,18964.85712313192],[18964.85712313192,21553.241750711244],[21553.241750711244,24494.897427831795],[24494.897427831795,27838.03972227065],[27838.03972227065,31637.464817394623],[31637.464817394623,35955.44765571728],[35955.44765571728,40862.76266397412],[40862.76266397412,46439.843790034625],[46439.843790034625,52778.102865379464],[52778.102865379464,59981.42790192414],[59981.42790192414,68167.88588120572],[68167.88588120572,77471.65794570907],[77471.65794570907,88045.23871132248],[88045.23871132248,100061.9357490223],[100061.9357490223,113718.71020384762],[113718.71020384762,129239.40511067926],[129239.40511067926,146878.41432092822],[146878.41432092822,166924.8521761233],[166924.8521761233,189707.29227194778],[189707.29227194778,215599.1529840161],[215599.1529840161,245024.81802750746],[245024.81802750746,278466.59237044415],[278466.59237044415,316472.60751236184],[316472.60751236184,359665.8057008049],[359665.8057008049,408754.1503425568],[408754.1503425568,464542.2299645975],[464542.2299645975,527944.4459209301],[527944.4459209301,599999.9999999966]],"underflow":2,"overflow":0},"impl":null},"get_transition_chain":{"dispatch":{"values":[0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"intervals":[[1000.0000000000086,1136.4832126482186],[1136.4832126482186,1291.5940926312048],[1291.5940926312048,1467.8750038309608],[1467.8750038309608,1668.2153001198121],[1668.2153001198121,1895.89868366906],[1895.89868366906,2154.6570268717232],[2154.6570268717232,2448.7315400542157],[2448.7315400542157,2782.942287553811],[2782.942287553811,3162.7671915737074],[3162.7671915737074,3594.4318187380427],[3594.4318187380427,4085.011421004358],[4085.011421004358,4642.546903447653],[4642.546903447653,5276.176619700187],[5276.176619700187,5996.28615525624],[5996.28615525624,6814.6785536835805],[6814.6785536835805,7744.767775855172],[7744.767775855172,8801.798563118215],[8801.798563118215,10003.096308094968],[10003.096308094968,11368.351028653215],[11368.351028653215,12919.940099556361],[12919.940099556361,14683.295031566244],[14683.295031566244,16687.31830973587],[16687.31830973587,18964.85712313192],[18964.85712313192,21553.241750711244],[21553.241750711244,24494.897427831795],[24494.897427831795,27838.03972227065],[27838.03972227065,31637.464817394623],[31637.464817394623,35955.44765571728],[35955.44765571728,40862.76266397412],[40862.76266397412,46439.843790034625],[46439.843790034625,52778.102865379464],[52778.102865379464,59981.42790192414],[59981.42790192414,68167.88588120572],[68167.88588120572,77471.65794570907],[77471.65794570907,88045.23871132248],[88045.23871132248,100061.9357490223],[100061.9357490223,113718.71020384762],[113718.71020384762,129239.40511067926],[129239.40511067926,146878.41432092822],[146878.41432092822,166924.8521761233],[166924.8521761233,189707.29227194778],[189707.29227194778,215599.1529840161],[215599.1529840161,245024.81802750746],[245024.81802750746,278466.59237044415],[278466.59237044415,316472.60751236184],[316472.60751236184,359665.8057008049],[359665.8057008049,408754.1503425568],[408754.1503425568,464542.2299645975],[464542.2299645975,527944.4459209301],[527944.4459209301,599999.9999999966]],"underflow":0,"overflow":0},"impl":null}},"external_transition_latency":{"values":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0],"intervals":[[1000.0000000000086,1136.4832126482186],[1136.4832126482186,1291.5940926312048],[1291.5940926312048,1467.8750038309608],[1467.8750038309608,1668.2153001198121],[1668.2153001198121,1895.89868366906],[1895.89868366906,2154.6570268717232],[2154.6570268717232,2448.7315400542157],[2448.7315400542157,2782.942287553811],[2782.942287553811,3162.7671915737074],[3162.7671915737074,3594.4318187380427],[3594.4318187380427,4085.011421004358],[4085.011421004358,4642.546903447653],[4642.546903447653,5276.176619700187],[5276.176619700187,5996.28615525624],[5996.28615525624,6814.6785536835805],[6814.6785536835805,7744.767775855172],[7744.767775855172,8801.798563118215],[8801.798563118215,10003.096308094968],[10003.096308094968,11368.351028653215],[11368.351028653215,12919.940099556361],[12919.940099556361,14683.295031566244],[14683.295031566244,16687.31830973587],[16687.31830973587,18964.85712313192],[18964.85712313192,21553.241750711244],[21553.241750711244,24494.897427831795],[24494.897427831795,27838.03972227065],[27838.03972227065,31637.464817394623],[31637.464817394623,35955.44765571728],[35955.44765571728,40862.76266397412],[40862.76266397412,46439.843790034625],[46439.843790034625,52778.102865379464],[52778.102865379464,59981.42790192414],[59981.42790192414,68167.88588120572],[68167.88588120572,77471.65794570907],[77471.65794570907,88045.23871132248],[88045.23871132248,100061.9357490223],[100061.9357490223,113718.71020384762],[113718.71020384762,129239.40511067926],[129239.40511067926,146878.41432092822],[146878.41432092822,166924.8521761233],[166924.8521761233,189707.29227194778],[189707.29227194778,215599.1529840161],[215599.1529840161,245024.81802750746],[245024.81802750746,278466.59237044415],[278466.59237044415,316472.60751236184],[316472.60751236184,359665.8057008049],[359665.8057008049,408754.1503425568],[408754.1503425568,464542.2299645975],[464542.2299645975,527944.4459209301],[527944.4459209301,599999.9999999966]],"underflow":0,"overflow":0},"accepted_transition_local_latency":null,"accepted_transition_remote_latency":{"values":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0],"intervals":[[1000.0000000000086,1136.4832126482186],[1136.4832126482186,1291.5940926312048],[1291.5940926312048,1467.8750038309608],[1467.8750038309608,1668.2153001198121],[1668.2153001198121,1895.89868366906],[1895.89868366906,2154.6570268717232],[2154.6570268717232,2448.7315400542157],[2448.7315400542157,2782.942287553811],[2782.942287553811,3162.7671915737074],[3162.7671915737074,3594.4318187380427],[3594.4318187380427,4085.011421004358],[4085.011421004358,4642.546903447653],[4642.546903447653,5276.176619700187],[5276.176619700187,5996.28615525624],[5996.28615525624,6814.6785536835805],[6814.6785536835805,7744.767775855172],[7744.767775855172,8801.798563118215],[8801.798563118215,10003.096308094968],[10003.096308094968,11368.351028653215],[11368.351028653215,12919.940099556361],[12919.940099556361,14683.295031566244],[14683.295031566244,16687.31830973587],[16687.31830973587,18964.85712313192],[18964.85712313192,21553.241750711244],[21553.241750711244,24494.897427831795],[24494.897427831795,27838.03972227065],[27838.03972227065,31637.464817394623],[31637.464817394623,35955.44765571728],[35955.44765571728,40862.76266397412],[40862.76266397412,46439.843790034625],[46439.843790034625,52778.102865379464],[52778.102865379464,59981.42790192414],[59981.42790192414,68167.88588120572],[68167.88588120572,77471.65794570907],[77471.65794570907,88045.23871132248],[88045.23871132248,100061.9357490223],[100061.9357490223,113718.71020384762],[113718.71020384762,129239.40511067926],[129239.40511067926,146878.41432092822],[146878.41432092822,166924.8521761233],[166924.8521761233,189707.29227194778],[189707.29227194778,215599.1529840161],[215599.1529840161,245024.81802750746],[245024.81802750746,278466.59237044415],[278466.59237044415,316472.60751236184],[316472.60751236184,359665.8057008049],[359665.8057008049,408754.1503425568],[408754.1503425568,464542.2299645975],[464542.2299645975,527944.4459209301],[527944.4459209301,599999.9999999966]],"underflow":0,"overflow":0},"snark_worker_transition_time":null,"snark_worker_merge_time":{"values":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0],"intervals":[[1000.0000000000086,1136.4832126482186],[1136.4832126482186,1291.5940926312048],[1291.5940926312048,1467.8750038309608],[1467.8750038309608,1668.2153001198121],[1668.2153001198121,1895.89868366906],[1895.89868366906,2154.6570268717232],[2154.6570268717232,2448.7315400542157],[2448.7315400542157,2782.942287553811],[2782.942287553811,3162.7671915737074],[3162.7671915737074,3594.4318187380427],[3594.4318187380427,4085.011421004358],[4085.011421004358,4642.546903447653],[4642.546903447653,5276.176619700187],[5276.176619700187,5996.28615525624],[5996.28615525624,6814.6785536835805],[6814.6785536835805,7744.767775855172],[7744.767775855172,8801.798563118215],[8801.798563118215,10003.096308094968],[10003.096308094968,11368.351028653215],[11368.351028653215,12919.940099556361],[12919.940099556361,14683.295031566244],[14683.295031566244,16687.31830973587],[16687.31830973587,18964.85712313192],[18964.85712313192,21553.241750711244],[21553.241750711244,24494.897427831795],[24494.897427831795,27838.03972227065],[27838.03972227065,31637.464817394623],[31637.464817394623,35955.44765571728],[35955.44765571728,40862.76266397412],[40862.76266397412,46439.843790034625],[46439.843790034625,52778.102865379464],[52778.102865379464,59981.42790192414],[59981.42790192414,68167.88588120572],[68167.88588120572,77471.65794570907],[77471.65794570907,88045.23871132248],[88045.23871132248,100061.9357490223],[100061.9357490223,113718.71020384762],[113718.71020384762,129239.40511067926],[129239.40511067926,146878.41432092822],[146878.41432092822,166924.8521761233],[166924.8521761233,189707.29227194778],[189707.29227194778,215599.1529840161],[215599.1529840161,245024.81802750746],[245024.81802750746,278466.59237044415],[278466.59237044415,316472.60751236184],[316472.60751236184,359665.8057008049],[359665.8057008049,408754.1503425568],[408754.1503425568,464542.2299645975],[464542.2299645975,527944.4459209301],[527944.4459209301,599999.9999999966]],"underflow":0,"overflow":0}},"consensus_time_best_tip":{"slot_number":"1971","slots_per_epoch":"480"},"next_block_production":["Check_again","1592076600000"],"consensus_time_now":{"slot_number":"2037","slots_per_epoch":"480"},"consensus_mechanism":"proof_of_stake","consensus_configuration":{"delta":3,"k":20,"c":8,"c_times_k":160,"slots_per_epoch":480,"slot_duration":180000,"epoch_duration":86400000,"genesis_state_timestamp":"1591644600000","acceptable_network_delay":540000},"addrs_and_ports":{"external_ip":"157.245.86.42","bind_ip":"0.0.0.0","peer":{"host":"0.0.0.0","libp2p_port":8302,"peer_id":"12D3KooWLpLiRs9WUdx2SKGtrF39xBbW8g12HJmUoacfdRy7TCpU"},"libp2p_port":8302,"client_port":8301}}
```
Status:

```json
{"OS_type":"Unix","Release":"4.19.0-0.bpo.6-amd64","Machine":"x86_64","Sys_name":"Linux","Exception":"(monitor.ml.Error\n (Failure \"local state desynced after applying diffs to full frontier\")\n (\"Raised at file \\\"stdlib.ml\\\", line 33, characters 17-33\"\n \"Called from file \\\"src/lib/debug_assert/debug_assert.ml\\\" (inlined), line 1, characters 25-33\"\n \"Called from file \\\"src/lib/transition_frontier/full_frontier/full_frontier.ml\\\", line 606, characters 4-1023\"\n \"Called from file \\\"src/lib/transition_frontier/transition_frontier.ml\\\", line 292, characters 4-93\"\n \"Called from file \\\"src/lib/transition_handler/processor.ml\\\", line 57, characters 10-68\"\n \"Called from file \\\"src/lib/rose_tree/rose_tree.ml\\\", line 79, characters 18-24\"\n \"Called from file \\\"src/deferred_or_error.ml\\\", line 101, characters 23-33\"\n \"Called from file \\\"src/lib/transition_handler/processor.ml\\\", line 285, characters 21-570\"\n \"Called from file \\\"src/result.ml\\\", line 151, characters 9-15\"\n \"Caught by monitor coda\"))","Command":"Command: (coda daemon -peer\n $SEED1 \n -peer\n $SEED2\n -run-snark-worker\n 4vsRCVbWUyT9Zuh2U3YZtAYq1V6xwWWhBfuDU9ymJFJsCddQSsAzHoexMmqsecrRLiVoafy5aA1wS8DCRYh2yd97wfe9jZV5HnYt4tCADk9Qq4yAr7Fxu6UcqDFyaq8Q28unt9FrrntVL2wy\n -snark-worker-fee 0.000000001 -block-producer-key /root/privkey\n -block-producer-password $PASSWORD)","Coda_branch":"feature/bump-genesis-timestamp","Coda_commit":"3e9b1748183e653a7891adea1fef07c8e1a7dfcd"}
```

**Comment by pkrasam** [comment] 2020-06-13 13:13
Have you tried `-block-producer-pubkey $CODA_PUBLIC_KEY`?

**Comment by garethtdavies** [comment] 2020-06-13 14:14
@k while you didn't paste the fatal part of the message it is most likely this issue https://github.com/CodaProtocol/coda/issues/5059

This is a known and transient issue. It's likely not related to how you started your node but when. I've also experienced this many times when restarting a node or joining a new node to the network. It'll actually likely resolve itself eventually but there is more discussion on the linked issue.

**Comment by bkase** [comment] 2020-06-16 20:22
Thanks @garethtdavies ! Let's assume it's a dupe of #5059 for now

**Closed by bkase** 2020-06-16 20:22 UTC
