### ISSUE TITLE
testnet 3.2b- daemon crashed on importing keys

### ISSUE THREAD

**Issue by Cris-F** [CodaProtocol/coda#5058] opened 2020-06-10 00:47 UTC
testnet 3.2b- daemon crashed on importing keys

Hi as it says there ^^^ :)

[coda_crash_report_2020-06-10_00-38-59.275042.tar.gz](https://github.com/CodaProtocol/coda/files/4755558/coda_crash_report_2020-06-10_00-38-59.275042.tar.gz)

**Comment by bkase** [comment] 2020-06-23 17:42
```
{"timestamp":"2020-06-10 00:38:58.827074Z","level":"Fatal","source":{"module":"Init__Coda_run","location":"File \"src/app/cli/src/init/coda_run.ml\", line 621, characters 56-63"},"message":"Unhandled top-level exception: $exn\nGenerating crash report","metadata":{"exn":"(monitor.ml.Error\n  (Failure \"local state desynced after applying diffs to full frontier\")\n  (\"Raised at file \\\"stdlib.ml\\\", line 33, characters 17-33\"\n    \"Called from file \\\"src/lib/debug_assert/debug_assert.ml\\\" (inlined), line 1, characters 25-33\"\n    \"Called from file \\\"src/lib/transition_frontier/full_frontier/full_frontier.ml\\\", line 606, characters 4-1023\"\n    \"Called from file \\\"src/lib/transition_frontier/transition_frontier.ml\\\", line 292, characters 4-93\"\n    \"Called from file \\\"src/lib/transition_handler/processor.ml\\\", line 57, characters 10-68\"\n    \"Called from file \\\"src/lib/rose_tree/rose_tree.ml\\\", line 79, characters 18-24\"\n    \"Called from file \\\"src/deferred_or_error.ml\\\", line 101, characters 23-33\"\n    \"Called from file \\\"src/deferred0.ml\\\", line 56, characters 64-69\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"\n    \"Caught by monitor coda\"))","host":"116.202.80.59","peer_id":"12D3KooWApkee2AgsWQNWxonp3v8Ru5gBmBHBpF8sQfhRNFhnGcv","pid":27061,"port":8302}}
```

Thanks for reporting!

This is a dupe of #5059 . The mitigation, for now, is wait an hour or so and try again :o

**Closed by bkase** 2020-06-23 17:42 UTC
Labels: testnet-bug
