### ISSUE TITLE
Kademlia causes node to die nondeterministically when starting up

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#2971] opened 2019-07-24 18:18 UTC
Sometimes when starting up (we've observed only on macOS), the node will die with a kademlia error.

```
    (monitor.ml.Error (Kademlia.Membership.Child_died)
  ("Raised at file \"src/lib/kademlia/membership.ml\", line 233, characters 18-34"
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5"
    "Called from file \"src/job_queue.ml\", line 170, characters 6-47"
    "Caught by monitor coda"))
```

This happened to @deepthiskumar , it's possible that there was a dangling Kademlia process that needed to be killed.

Restarting the computer seems to mitigate this. If this happens to you, also try `ps aux | grep kademlia` and kill any processes you see there before restarting your node.

**Comment by imeckler** [comment] 2019-07-26 22:12
This is caused by kademlia dying. There are multiple possible explanations:

- could not connect to any seed peer (internet or port forwarding issue)
- kademlia process already exists

This could be fixed by adding error handling to spawning kademlia for these possible cases.

**Comment by imeckler** [comment] 2019-08-16 21:44
@cmr added a workaround in #3071

**Closed by imeckler** 2019-08-16 21:44 UTC
Labels: impacts users
