### ISSUE TITLE
[Crash] indexed pool nonces inconsistent when adding from backtrack

### ISSUE THREAD

**Issue by gregbostrom** [CodaProtocol/coda#4078] opened 2019-12-13 14:03 UTC
[coda_crash_report_2019-12-13_09-06-29.053696.tar.gz](https://github.com/CodaProtocol/coda/files/3961128/coda_crash_report_2019-12-13_09-06-29.053696.tar.gz)
```
[2019-12-13 09:06:28.927490]Init__Coda_run: Unhandled top-level exception: $exn
Generating crash report
$exn = "(monitor.ml.Error\n  (Failure\n     \"indexed pool nonces inconsistent when adding from backtrack. Trying to add ((payload\\\n    \\n  ((common\\\n    \\n    ((f
ee 1)
```

**Comment by gregbostrom** [comment] 2019-12-14 20:01
It just happened again.
```
$ cat coda.version 
bd5715a3f00754869498083b2506db776a7047e2
```
[coda_crash_report_2019-12-14_19-46-14.665111.tar.gz](https://github.com/CodaProtocol/coda/files/3964285/coda_crash_report_2019-12-14_19-46-14.665111.tar.gz)

**Comment by gregbostrom** [comment] 2019-12-15 21:10
Another occurrence.
[coda_crash_report_2019-12-15_20-42-24.806997.tar.gz](https://github.com/CodaProtocol/coda/files/3965458/coda_crash_report_2019-12-15_20-42-24.806997.tar.gz)

**Comment by bkase** [comment] 2019-12-19 00:31
Dupe of #3644 ; thanks for reporting!

**Closed by bkase** 2019-12-19 00:31 UTC

**Comment by bkase** [comment] 2019-12-19 00:36
Actually let's dedupe with #4066
