### ISSUE TITLE
Snark node crash

### ISSUE THREAD

**Issue by wjdfx** [CodaProtocol/coda#4088] opened 2019-12-14 11:54 UTC
`Dec 14 10:59:39 ip-172-25-236-201 bash[20479]: Generating crash report`

[crash_log.log](https://github.com/CodaProtocol/coda/files/3963787/crash_log.log)

**Comment by gregbostrom** [comment] 2019-12-14 16:06
```
exn: "(monitor.ml.Error\n  (Failure\n     \"indexed pool nonces inconsistent when adding from backtrack. 
```
Looks like another occurrence of 
https://github.com/CodaProtocol/coda/issues/4078

**Comment by bkase** [comment] 2019-12-19 00:31
Dupe of #3644 ; thanks for reporting!

**Closed by bkase** 2019-12-19 00:31 UTC

**Comment by bkase** [comment] 2019-12-19 00:36
Actually let's dedupe with #4066
