### ISSUE TITLE
3.2b is crashed

### ISSUE THREAD

**Issue by StarLI-Trapdoor** [CodaProtocol/coda#5056] opened 2020-06-10 00:28 UTC

**Comment by StarLI-Trapdoor** [comment] 2020-06-10 00:29
[coda_crash_report_2020-06-10_00-21-39.607477.tar.gz](https://github.com/CodaProtocol/coda/files/4755521/coda_crash_report_2020-06-10_00-21-39.607477.tar.gz)

**Comment by StarLI-Trapdoor** [comment] 2020-06-10 06:58
I think the crash is related with "root" account on Ubuntu.

With root account, the following warning shows up when installing:

syncing data to disk ... ok

Success. You can now start the database server using:

/usr/lib/postgresql/10/bin/pg_ctl -D /var/lib/postgresql/10/main -l logfile start
Ver Cluster Port Status Owner Data directory Log file
10 main 5432 down postgres /var/lib/postgresql/10/main /var/log/postgresql/postgresql-10-main.log
update-alternatives: using /usr/share/postgresql/10/man/man1/postmaster.1.gz to provide /usr/share/man/man1/postmaster.1.gz (postmaster.1.gz) in auto mode
Setting up postgresql (10+190ubuntu0.1) ...
Setting up coda-testnet-postake-medium-curves (0.0.12-beta+406048-feature-bump-genesis-timestamp-3e9b174-PV48525e92) ...
Processing triggers for systemd (237-3ubuntu10.38) ...
Processing triggers for ureadahead (0.100.0-20) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...

**Comment by StarLI-Trapdoor** [comment] 2020-06-10 06:58
If switching to normal user, the node can be started smoothly :)

**Comment by bkase** [comment] 2020-06-23 17:46
```
{"timestamp":"2020-06-10 00:21:36.915157Z","level":"Fatal","source":{"module":"Init__Coda_run","location":"File \"src/app/cli/src/init/coda_run.ml\", line 621, characters 56-63"},"message":"Unhandled top-level exception: $exn\nGenerating crash report","metadata":{"exn":"(monitor.ml.Error\n  \"Assert_failure src/lib/block_producer/block_producer.ml:598:16\"\n  (\"Raised at file \\\"src/lib/block_producer/block_producer.ml\\\", line 598, characters 16-234\"\n    \"Called from file \\\"src/result.ml\\\", line 151, characters 9-15\"\n    \"Caught by monitor coda\"))","host":"208.123.119.170","peer_id":"12D3KooWBP2fCeNaNUkvTczFk1KiFkSjaw5nZhaBdKYWgQYQLWGu","pid":20016,"port":8302}}
```

Thanks for reporting! This is a dupe of #5079

**Closed by bkase** 2020-06-23 17:46 UTC
Labels: testnet-bug
