### ISSUE TITLE
daemon crash report

### ISSUE THREAD

**Issue by sundafa** [CodaProtocol/coda#3956] opened 2019-11-20 06:00 UTC
Coming soon block
The daemon is crashing
[coda_crash_report_2019-11-20_05-47-56.011384.tar.gz](https://github.com/CodaProtocol/coda/files/3867532/coda_crash_report_2019-11-20_05-47-56.011384.tar.gz)

**Comment by o1pranay** [comment] 2019-11-28 00:00
```
{"OS_type":"Unix","Release":"4.15.0-60-generic","Machine":"x86_64","Sys_name":"Linux",
"Exception":"(monitor.ml.Error \"Assert_failure lib/network_pool/indexed_pool.ml:529:8\"
  (\"Raised at file \\\"lib/network_pool/indexed_pool.ml\\\", line 529, characters 8-69\"
    \"Called from file \\\"lib/network_pool/transaction_pool.ml\\\", line 534, characters 30-193\"
    \"Called from file \\\"lib/network_pool/network_pool_base.ml\\\", line 26, characters 15-65\"
    \"Called from file \\\"src/pipe.ml\\\", line 827, characters 4-56\"
    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"
    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"
    \"Caught by monitor coda\")\n
```

**Comment by o1pranay** [comment] 2019-11-28 00:02
Seems like this one is a duplicate of #3931, so going to close this one out -- thanks for reporting @sundafa !

**Closed by o1pranay** 2019-11-28 00:02 UTC
