### ISSUE TITLE
Node startup error

### ISSUE THREAD

**Issue by akramhussein** [CodaProtocol/coda#5054] opened 2020-06-10 00:10 UTC
```
2020-06-09 23:58:57 UTC [Info] Coda daemon is now doing ledger catchup
2020-06-09 23:59:20 UTC [Info] Running async shutdown handler: "Close transition frontier, if exists"
(monitor.ml.Error
 (Sys_error
  "/home/user
/.coda-config/coda_crash_report_2020-06-09_23-58-57.894476/coda_status.json: No such file or directory")
 ("Raised by primitive operation at file \"stdlib.ml\", line 316, characters 29-55"
  "Called from file \"stdlib.ml\" (inlined), line 321, characters 2-74"
  "Called from file \"write.ml\", line 470, characters 11-24"
  "Called from file \"src/app/cli/src/init/coda_run.ml\", line 265, characters 2-40"
  "Called from file \"src/deferred1.ml\", line 17, characters 40-45"
  "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5"
  "Called from file \"src/job_queue.ml\", line 171, characters 6-47"))
```

[coda_crash_report_2020-06-09_23-53-05.871026.tar.gz](https://github.com/CodaProtocol/coda/files/4755469/coda_crash_report_2020-06-09_23-53-05.871026.tar.gz)

**Comment by bkase** [comment] 2020-06-23 19:57
```
{"timestamp":"2020-06-09 23:24:56.297259Z","level":"Fatal","source":{"module":"Init__Coda_run","location":"File \"src/app/cli/src/init/coda_run.ml\", line 621, characters 56-63"},"message":"Unhandled top-level exception: $exn\nGenerating crash report","metadata":{"exn":"(monitor.ml.Error\n  \"Assert_failure src/lib/block_producer/block_producer.ml:598:16\"\n  (\"Raised at file \\\"src/lib/block_producer/block_producer.ml\\\", line 598, characters 16-234\"\n    \"Called from file \\\"src/result.ml\\\", line 151, characters 9-15\"\n    \"Caught by monitor coda\"))","host":"146.0.138.136","peer_id":"12D3KooWDbzbkXpYizZQmn1YBDbdQBhfdyCABzE2fJ74t27Xvvjj","pid":27491,"port":8302}}
```

This is a dupe of #5079 . Thanks for reporting!

**Closed by bkase** 2020-06-23 19:57 UTC
Labels: testnet-bug
