### ISSUE TITLE
CrisF - coda_crash_report_2019-12-16_04-14-59.694998

### ISSUE THREAD

**Issue by Cris-F** [CodaProtocol/coda#4089] opened 2019-12-16 10:14 UTC
I returned to find my daemon down.  
Was running block producer and snark-worker simultaneously.
Hope this helps.
CrisF
[coda_crash_report_2019-12-16_04-14-59.694998.tar.gz](https://github.com/CodaProtocol/coda/files/3967443/coda_crash_report_2019-12-16_04-14-59.694998.tar.gz)

**Comment by bkase** [comment] 2019-12-19 00:34
Thanks for reporting! Dupe of #3644

**Closed by bkase** 2019-12-19 00:34 UTC

**Comment by bkase** [comment] 2019-12-19 00:35
Actually let's dedupe with #4066
