### ISSUE TITLE
"snark pool diff" to $peer failed

### ISSUE THREAD

**Issue by victorxu0411** [CodaProtocol/coda#4063] opened 2019-12-12 15:07 UTC
peer: { "host": "3.14.86.143", "discovery_port": 8303, "communication_port": 8302 }
2019-12-12 02:59:10 UTC [Info] Clearing disconnected peer set : (((host 3.14.86.143) (discovery_port 8303) (communication_port 8302))
 ((host 192.187.122.162) (discovery_port 8303) (communication_port 8302)))
2019-12-12 02:59:10 UTC [Info] Connected to some peers [[host : 3.14.86.143, discovery_port : 8303, communication_port : 8302]]
2019-12-12 02:59:17 UTC [Error] RPC call raised an exception: $exn
	exn: "(\"connection attempt timeout\" 103.72.147.189:8302 src/tcp.ml:120:11)"
2019-12-12 02:59:17 UTC [Error] Broadcasting message "transaction pool diff" to $peer failed: $error
	peer: {
  "host": "103.72.147.189",
  "discovery_port": 8303,
  "communication_port": 8302
}
	error: "(\"connection attempt timeout\" 103.72.147.189:8302 src/tcp.ml:120:11)"
2019-12-12 02:59:25 UTC [Error] RPC call raised an exception: $exn
	exn: "(\"connection attempt timeout\" 103.72.147.189:8302 src/tcp.ml:120:11)"
2019-12-12 02:59:25 UTC [Error] Broadcasting message "snark pool diff" to $peer failed: $error
	peer: {
  "host": "103.72.147.189",
  "discovery_port": 8303,
  "communication_port": 8302
}
	error: "(\"connection attempt timeout\" 103.72.147.189:8302 src/tcp.ml:120:11)"
2019-12-12 02:59:50 UTC [Error] RPC call raised an exception: $exn
	exn: "(\"connection attempt timeout\" 103.72.147.189:8302 src/tcp.ml:120:11)"
2019-12-12 02:59:50 UTC [Error] RPC call raised an exception: $exn
	exn: "(\"connection attempt timeout\" 87.255.8.92:8302 src/tcp.ml:120:11)"
2019-12-12 02:59:51 UTC [Error] Broadcasting message "snark pool diff" to $peer failed: $error
	peer: {
  "host": "103.72.147.189",
  "discovery_port": 8303,
  "communication_port": 8302
}
	error: "(\"connection attempt timeout\" 103.72.147.189:8302 src/tcp.ml:120:11)"
2019-12-12 02:59:51 UTC [Error] Broadcasting message "snark pool diff" to $peer failed: $error
	peer: { "host": "87.255.8.92", "discovery_port": 8303, "communication_port": 8302 }
	error: "(\"connection attempt timeout\" 87.255.8.92:8302 src/tcp.ml:120:11)"
2019-12-12 02:59:54 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
	exn: "(monitor.ml.Error \"Assert_failure lib/network_pool/indexed_pool.ml:529:8\"\n  (\"Raised at file \\\"lib/network_pool/indexed_pool.ml\\\", line 529, characters 8-69\"\n    \"Called from file \\\"lib/network_pool/transaction_pool.ml\\\", line 534, characters 30-193\"\n    \"Called from file \\\"lib/network_pool/network_pool_base.ml\\\", line 26, characters 15-65\"\n    \"Called from file \\\"src/pipe.ml\\\", line 827, characters 4-56\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"\n    \"Caught by monitor coda\"))"

  ☠  Coda daemon crashed. The Coda Protocol developers would like to know why!

it just crashed after run for a few hours.
[coda_crash_report_2019-12-12_02-59-54.703848.tar.gz](https://github.com/CodaProtocol/coda/files/3956386/coda_crash_report_2019-12-12_02-59-54.703848.tar.gz)

**Comment by bkase** [comment] 2019-12-19 00:32
Dupe of #3644 ; thanks for reporting!

**Closed by bkase** 2019-12-19 00:32 UTC

**Comment by bkase** [comment] 2019-12-19 00:35
Actually lets dedupe with #4066
