### ISSUE TITLE
testnet 3.3 ☠  Coda Daemon crashed. genesis_ledger_accounts download error. 

### ISSUE THREAD

**Issue by xiaoxin-crypto** [CodaProtocol/coda#5987] opened 2020-09-17 11:16 UTC
* command
```
coda daemon -peer $SEED1
```
* version
```
~# coda version
Commit fdc283b on branch master
```
* error log
```
	error: "(monitor.ml.Error\n (\"Process.run failed\"\n  ((prog curl)\n   (args\n    (--fail -o\n     /tmp/s3_cache_dir/genesis_ledger_accounts_e7fd308899bca6956b093b635988ea06630adbf540e13d38dcd2f7ab629da53c_f094d0eb814dbbff2f41f3f69c414331566f2c4a884c309944899ea59f101b9a.tar.gz\n     https://s3-us-west-2.amazonaws.com/snark-keys.o1test.net/genesis_ledger_accounts_e7fd308899bca6956b093b635988ea06630adbf540e13d38dcd2f7ab629da53c_f094d0eb814dbbff2f41f3f69c414331566f2c4a884c309944899ea59f101b9a.tar.gz))\n   (exit_status (Exit_non_zero 22)) (stdout \"\")\n   (stderr\n    (\"  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\"\n     \"                                 Dload  Upload   Total   Spent    Left  Speed\"\n     \"\\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\"\n     \"curl: (22) The requested URL returned error: 404 Not Found\" \"\"))))\n (\"Raised at file \\\"src/error.ml\\\" (inlined), line 9, characters 14-30\"\n  \"Called from file \\\"src/or_error.ml\\\", line 72, characters 17-32\"\n  \"Called from file \\\"src/deferred1.ml\\\", line 17, characters 40-45\"\n  \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n  \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"))"
```
* crash report
[coda_crash_report_2020-09-17_11-04-01.607135.tar.gz](https://github.com/CodaProtocol/coda/files/5238671/coda_crash_report_2020-09-17_11-04-01.607135.tar.gz)

**Comment by emberian** [comment] 2020-09-19 14:48
this error is not related to the crash. the actual crash is a dupe of #6001

**Closed by emberian** 2020-09-19 14:48 UTC
