### ISSUE TITLE
Testnet 3.3 unable to start the node after I run: coda daemon -peer $SEED1, Coda Daemon crashed

### ISSUE THREAD

**Issue by UbikCapital** [CodaProtocol/coda#6006] opened 2020-09-17 20:54 UTC
Testnet 3.3 unable to start the node 

  error: "(monitor.ml.Error\n (\"Process.run failed\"\n  ((prog curl)\n   (args\n    (--fail -o\n     /tmp/s3_cache_dir/genesis_ledger_accounts_e7fd308899bca6956b093b635988ea06630adbf540e13d38dcd2f7ab629da53c_f094d0eb814dbbff2f41f3f69c414331566f2c4a884c309944899ea59f101b9a.tar.gz\n     https://s3-us-west-2.amazonaws.com/snark-keys.o1test.net/genesis_ledger_accounts_e7fd308899bca6956b093b635988ea06630adbf540e13d38dcd2f7ab629da53c_f094d0eb814dbbff2f41f3f69c414331566f2c4a884c309944899ea59f101b9a.tar.gz))\n   (exit_status (Exit_non_zero 22)) (stdout \"\")\n   (stderr\n    (\"  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\"\n
\"                                 Dload  Upload   Total   Spent    Left  Speed\"\n     \"\\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--
  0\\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\"\n     \"curl: (22) The requested URL returned error: 404 Not Found\" \"\"))))\n (\"Raised at file \\\"src/error.ml\\\" (inlined), line 9, characters 14-30\"\n  \"Called from file \\\"src/or_error.ml\\\", line 72, characters 17-32\"\n  \"Called from file \\\"src/deferred1.ml\\\", line 17, characters 40-45\"\n  \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n  \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"))"
2020-09-17 20:34:15 UTC [Info] Creating genesis ledger tar file for $root_hash at $path from database at $dir
        root_hash: "3NLDMBjXomomCVeMu54X8qXYZDuCzKM4QJaezgdUX57yHWqNgjmM"
        path: "/root/.coda-config/genesis_ledger_f1c1b1bae67e1ec8ffdf91121ec34c7c97933fd86b727ebd8a5421b7f12a8ece.tar.gz"
        dir: "/tmp/coda_cache_dir/426b989d-3def-346b-167e-124c4a88587a"
2020-09-17 20:34:15 UTC [Info] Linking ledger file $tar_path to $named_tar_path
        tar_path: "/root/.coda-config/genesis_ledger_f1c1b1bae67e1ec8ffdf91121ec34c7c97933fd86b727ebd8a5421b7f12a8ece.tar.gz"
        named_tar_path: "/root/.coda-config/genesis_ledger_release_f094d0eb814dbbff2f41f3f69c414331566f2c4a884c309944899ea59f101b9a.tar.gz"
2020-09-17 20:34:16 UTC [Info] Genesis proof file $path does not exist
        path: "/root/.coda-config/genesis_proof_4e3894c8dc5e2d9a6485cb766d38ab2006e71977175e18abfffceecefd992c74"
2020-09-17 20:34:16 UTC [Info] Found genesis proof file at $path
        path: "/var/lib/coda/genesis_proof_4e3894c8dc5e2d9a6485cb766d38ab2006e71977175e18abfffceecefd992c74"
2020-09-17 20:34:16 UTC [Info] Loaded ledger from $ledger_file and genesis proof from $proof_file
        ledger_file: "/root/.coda-config/genesis_ledger_release_f094d0eb814dbbff2f41f3f69c414331566f2c4a884c309944899ea59f101b9a.tar.gz"
        proof_file: "/var/lib/coda/genesis_proof_4e3894c8dc5e2d9a6485cb766d38ab2006e71977175e18abfffceecefd992c74"
2020-09-17 20:34:17 UTC [Info] Setting current protocol version to "0.1.0" from compile-time config
2020-09-17 20:35:11 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
        exn: "(monitor.ml.Error\n  ((rpc_error (Connection_closed (\"EOF or connection closed\")))\n    (connection_description\n      (\"Client connected via TCP\" (m12386.contaboserver.net 45811)))\n    (rpc_tag worker_init_rpc_1) (rpc_version 0))\n  (\"Raised at file \\\"src/error.ml\\\" (inlined), line 9, characters 14-30\"\n    \"Called from file \\\"src/or_error.ml\\\", line 72, characters 17-32\"\n    \"Called from file \\\"src/deferred1.ml\\\", line 17, characters 40-45\"\n    \"Called from
file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"))"

  ☠  Coda Daemon crashed.
   The Coda Protocol developers would like to know why!

    Please:
      Open an issue:
        <https://github.com/CodaProtocol/coda/issues/new>

      Briefly describe what you were doing and attach the crash report /root/.coda-config/coda_crash_report_2020-09-17_20-35-12.005070.tar.gz
[coda_crash_report_2020-09-17_20-35-12.005070.tar.gz](https://github.com/CodaProtocol/coda/files/5241762/coda_crash_report_2020-09-17_20-35-12.005070.tar.gz)

**Comment by garethtdavies** [comment] 2020-09-18 18:36
This is a duplicate of https://github.com/CodaProtocol/coda/issues/6001

**Comment by emberian** [comment] 2020-09-19 00:39
Closing as dupe

**Closed by emberian** 2020-09-19 00:39 UTC
